### ISSUE TITLE
Keeping svg in sync with built dart object graph

### ISSUE THREAD

**Issue by gedw99** [dnfield/flutter_path_drawing#1]
I have been playing around with this.

I am not thinking about how the user can edit the visual representation  of the svg.

I think it only makes sense to provide actions, which then manipulate the SVG and then update the object graph.
The reason is because it's a one way flow and so much easier to reason about and avoid side effects.

I can work on this. Is this approach agreeable to how you would do this use case ? Is it welcomed ?

**Comment by dnfield** [comment]
Did you mean to open this here or in https://github.com/dnfield/flutter_svg?

I'd rather not implement a DOM model for SVG in that.  Ideally, you parse the XML once and discard the raw XML data as quickly as possible to keep memory usage low.  However, I'd be very open to the idea of manipulating the intermediate structure (the `Drawable` classes) that the SVG parses into.  There's some discussion of that at dnfield/flutter_svg#2 - any ideas are welcome, and if you have some code I'd be happy to look at a PR.  That said, I really want to keep it as something that will make life good in terms of backwards compatibility/maintainability as the SVG parsing and rendering develops.

**Comment by gedw99** [comment]
oops- yes i meant to do it in the svg repo.

Anyway, i looked at the #2, but its not what i had in mind.
- agree that its best to dumb the svg out on memory ASAP ; good point.

Manipulating the drawable classes is something that works for me. But i need to make it data driven in a generic way to make an SVG editor, which is the best way to describe this. 
I think i should not contribute here right now. I can see you want a one way ple flow for now.

I think i might mess around with flat buffers as the Intermediate data structures.
SO the data path is: svg --> flat buffers ( on disk or mem) --> flutter.
Mutations path being: user action --> flat buffer changes --> update flutter at the exact point.

**Comment by gedw99** [comment]
I see what you mean. Cross that bridge later..

What do you think about Flatbuffers as the intermediate format ?
Your kind of the expert on FB and Dart right now

I am using golang and flat buffers and totally kicking myself for sticking
with grpc and protobuf for 2 years :)

**Comment by dnfield** [comment]
That'd be my preference.  I'm not really sure how much boost it giveS on the dart side. S protobuf, but it has a lot of potential on the native side for sure and I'm hoping that path opens up for flutter.

**Comment by gedw99** [comment]
great. I am using it currently in golang for DB and Network stuff and so
using it on the client side on flutter makes lots of sense.
I will wait until your PR for Dart flatbuffers hits and then get beach
programming on it :)
