### ISSUE TITLE
There's no way to maintain consistent dashes for multiple, connected, dashed beziers.

### ISSUE THREAD

**Issue by modulovalue** [dnfield/flutter_path_drawing#11]
See the following image.

(This image shows a Path where multiple connected cubics are drawn that contain inconsistent dashes)
<img width="1036" alt="Bildschirmfoto 2020-07-29 um 18 18 44" src="https://user-images.githubusercontent.com/24444584/88825839-4fc20080-d1c8-11ea-9db4-8d505de86215.png">

It's worse for variable dash lengths and offsets where visual inconsistencies are much more noticeable.

The following code was used to draw the curves, with dashPath applied to it afterwards.
```dart
            final path = Path();
            for (final cubic in a.self) {
              path
                ..moveTo(... ,...) // first point
                ..cubicTo(..., ..., ..., ..., ..., ...); // second, third, fourth point
            }
```

**Comment by modulovalue** [comment]
>It's worse for variable dash lengths and offsets where visual inconsistencies are much more noticeable.

Here's an example for `CircularIntervalList([40.0, 10.0])` 

<img width="1267" alt="Bildschirmfoto 2020-07-29 um 22 20 37" src="https://user-images.githubusercontent.com/24444584/88849503-421d7280-d1ea-11ea-9f80-de36857e7a42.png">

**Comment by modulovalue** [comment]
@dnfield

**Comment by dnfield** [comment]
It would help to have a full reproducible sample for this

**Comment by modulovalue** [comment]
```dart
import 'package:flutter/material.dart';
import 'package:path_drawing/path_drawing.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: CustomPaint(
          painter: Example(),
        ),
      ),
    );
  }
}

class Example extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = Colors.red
      ..style = PaintingStyle.stroke
      ..strokeWidth = 8.0;

    Iterable<void Function()> drawAll(Path p) => [
          () => canvas.drawPath(p, paint),
          () => canvas.drawPath(dashPath(p, dashArray: CircularIntervalList([5.0])), paint),
          () => canvas.drawPath(dashPath(p, dashArray: CircularIntervalList([5.0, 1.0])), paint),
        ];
    [
      ...drawAll(Path() //
        ..lineTo(50.0, 50.0)
        ..lineTo(150.0, 50.0)),
      ...drawAll(Path() //
        ..cubicTo(50, 50, 50, 150, 100.0, 100.0)
        ..moveTo(100.0, 100.0)
        ..cubicTo(250.0, 150.0, 250.0, 250.0, 250.0, 250.0)),
      ...drawAll(Path() //
        ..cubicTo(50, 50, 50, 150, 100.0, 100.0)
        ..cubicTo(250.0, 150.0, 250.0, 250.0, 250.0, 250.0)),
    ].forEach((drawPath) {
      drawPath();
      canvas.translate(0.0, 70.0);
    });
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => true;
}

```

The failure to draw the path seems to be caused by the moveTo call. (as seen in curve 4, 5, 6)

<img width="294" alt="Bildschirmfoto 2020-07-31 um 19 39 29" src="https://user-images.githubusercontent.com/24444584/89061752-8ed98880-d365-11ea-934b-aee62c496ca1.png">

There's another issue, even for straight lines:
<img width="34" alt="Bildschirmfoto 2020-07-31 um 19 41 10" src="https://user-images.githubusercontent.com/24444584/89061881-ca745280-d365-11ea-9218-ddc90acc9fc8.png">

If you zoom in close enough you should see that that's not the right way to draw that segment.

**Comment by modulovalue** [comment]
Since drawing connected beziers in the form of
`(a, b, c, d) (d, e, f, g) (g, h, i, j) ...` can be accomplished with only one moveTo call at the beginning, This is not an issue anymore.

I'll open a new one for the other one.
