### ISSUE TITLE
DashOffset causes missing paths at the beginning of a path.

### ISSUE THREAD

**Issue by modulovalue** [dnfield/flutter_path_drawing#13]
![ezgif-2-7373e18f8a23](https://user-images.githubusercontent.com/24444584/89356462-2caeb980-d6be-11ea-9d5b-23cfb3b0b5ad.gif)

Paths at the beginning (bottom of the gif) should be drawn partially if a DashOffset is specified.
See [this](https://codepen.io/team/css-tricks/pen/QygqBM) CodePen for the expected behavior.

**Comment by modulovalue** [comment]
@dnfield

**Comment by dnfield** [comment]
I agree this is a problem but don't have a lot of time to look at it at the moment. I'd be happy to review a PR that fixes it.

**Comment by modulovalue** [comment]
I'm closing this issue because it is stale and will most likely be not needed once https://github.com/flutter/flutter/issues/112981 (which seems to be planned) will be implemented.
