### ISSUE TITLE
Add the ability to pass in your own memoized path metrics Iterable.

### ISSUE THREAD

**Issue by modulovalue** [dnfield/flutter_path_drawing#16]
Taken from the computeMetrics docs

```dart
  /// Calculating [PathMetric] objects is not trivial. The [PathMetrics] object
  /// returned by this method is a lazy [Iterable], meaning it only performs
  /// calculations when the iterator is moved to the next [PathMetric]. Callers
  /// that wish to memoize this iterable can easily do so by using
  /// [Iterable.toList] on the result of this method. In particular, callers
  /// looking for information about how many contours are in the path should
  /// either store the result of `path.computeMetrics().length`, or should use
  /// `path.computeMetrics().toList()` so they can repeatedly check the length,
  /// since calling `Iterable.length` causes traversal of the entire iterable.
  ///
```

Some use cases such as drawing arrows need path metrics. And since arrows are commonly 'dashed', one should be able to provide his own metrics as an optimization.

**Comment by dnfield** [comment]
Seems completely reasonable. Happy to review a PR that does so.

**Comment by modulovalue** [comment]
I'm closing this issue because it is stale and will most likely be not needed once https://github.com/flutter/flutter/issues/112981 (which seems to be planned) will be implemented.

**Comment by mateusfccp** [comment]
https://github.com/flutter/flutter/issues/110723 is actually P5, so I don't think we will have it anytime soon. It would be great to have this implemented.
