### ISSUE TITLE
Built paths

### ISSUE THREAD

**Issue by aloisdeniel** [dnfield/flutter_path_drawing#2]
A great feature would be to generate path dart code at compile code instead of parsing it at runtime (with code_builder).

**Comment by dnfield** [comment]
This is a good idea, and wouldn't be hard to implement in principle (i.e. to output the path commands to Dart code rather than actually doing it on a `Path`).  However, there's nothing currently in this library that's built for writing files to disk etc.

How would you see this working end to end?

**Comment by aloisdeniel** [comment]
I would use the `build_runner`package to generate the code, just like [built_value](https://github.com/google/built_value.dart) or my library [dioc](https://github.com/aloisdeniel/dioc/tree/master/dioc_generator).

You could scan annotated classes like this :

```dart
library example;

import 'package:dioc/src/container.dart';
import 'package:dioc/src/built_container.dart';

part "paths.g.dart";

abstract class Paths {
  @Path("M12 2.69l5.66 5.66a8 8 0 1 1-11.31 0z")
  Path get droplet;
}
```

And that would generate classes like :

```dart
library example;

import 'package:dioc/src/container.dart';
import 'package:dioc/src/built_container.dart';

part "paths.g.dart";
class _Paths {
  final Path _droplet;
  Path get droplet => this._droplet;
  static Path _buildDroplet() {
      var result = new Path();
      ///...
      return result;
   }
  _Paths() : this._droplet = _buildDroplet();
}

class PathsBuilder {
  static Paths build() {
    return new _Paths();
  }
}
```
I image that this would also be possible for generating the entire svg code, but paths can be a good start (and that is what I need at the moment :))

**Comment by dnfield** [comment]
This should be unblocked now that #3 is closed

I'll take a crack at it if I have time, but also would welcome a PR if you have something in mind for it.

**Comment by dnfield** [comment]
I should note that I'm leaning more towards code-gen at this point because it solves some problems around serialization of objects that are currently difficult to serialize (and potentially difficult to "futureproof") - in particular, Flutter's `Paint` and `Path` objects.

**Comment by aloisdeniel** [comment]
I'll do a PR with a code_builder based PathProxy as soon as I have time! :)

**Comment by dnfield** [comment]
Been fiddling with this on and off - things have changed since I last was trying to use build/build_runner, but I have a working prototype, check here in particular: 

https://github.com/dnfield/dart_path_parsing/blob/codegen/test/gen_test.svg_path.g.dart

I think it makes the most sense to just generate top-level variables, althought he way I'm doing it makes for a little more work for the end user (they have to get that `_$naming` right) and I'd be open to suggestions to improve that.

**Comment by dnfield** [comment]
I'm also wondering if this really belongs in the flutter_path_drawing or in the dart_path_parsing project.

I'm leaning towards moving it over to flutter_path_drawing

**Comment by aloisdeniel** [comment]
Cool, it seems good to me! I just hesitate to add lazy loading of path in my project.

```dart
Path _$droplet;
Path _$create_droplet() => _$droplet ?? new Path()
  ..moveTo(12.0, 2.6900000000000004)
  ..lineTo(17.66, 8.350000000000001)
  ..cubicTo(20.785700915139913, 11.473652786890238, 20.786807843109994,
      16.539925770319012, 17.662472197643723, 19.664944125212706)
  ..cubicTo(14.538136552177448, 22.789962480106404, 9.47186344782255,
      22.789962480106404, 6.347527802356277, 19.66494412521271)
  ..cubicTo(3.223192156890004, 16.539925770319016, 3.2242990848600837,
      11.473652786890238, 6.349999999999997, 8.350000000000001)
  ..close();
````

For the code location, if you look at `built_value`, the annotations are in a `built_value` package and the code generation logic in a `built_value_generator` package.

I would have put the two new packages in the `dart_path_parsing`repo for that purpose.

**Comment by dnfield** [comment]
I'll take a look at built value.

I don't mind lazy loading.  But at some point I think a reference to dart:ui will be helpful, for example to get the fill type.  That could be proxied, but why?

**Comment by dnfield** [comment]
As I think about it, it might be nice to just have a completely new repo for the built/codegen portion, e.g. `built_path`, which could have an annotations library and a generator library, similar to https://github.com/kevmoo/build_cli - this feels more akin to that project than built_value

I don't have an issue with splitting out the Dart parsing code because that code could be useful for non-flutter scenarios.  I'd like to avoid completely rearranging the flutter_path_drawing library (as well as potentially confusing/bloating the codebase there with unrelated generation code).

What do you think?

**Comment by aloisdeniel** [comment]
Yep, it is the best solution for me too.

And you could have the same repo structure for SVG parsing, rendering and code building.

**Comment by dnfield** [comment]
See here: https://github.com/dnfield/flutter_built_path

Going to close this issue.  Let's discuss further in that repo if you have any thoughts/suggestions/issues

And I'd still welcome any PRs/comments there!

**Comment by dnfield** [comment]
I'm going to hold off on publishing it for a day or so just to give it a little time to bake and make sure it all really makes sense/write some unit tests.
