### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by meysammahfouzi** [dnfield/flutter_path_drawing#4]
Could you please update the README file with some documentation and examples of drawing curved lines?

**Comment by dnfield** [comment]
This library might be poorly named.  It really is about parsing a path from svg syntax, and then being able to dash or trim the path.

I suspect you're looking for things like the cubicTo method on path...

**Comment by meysammahfouzi** [comment]
@dnfield You are right, I need to use `cubicTo`. Is it possible to draw bezier dashed lines with your library?

**Comment by meysammahfouzi** [comment]
I specifically would like to an example of how to call the `dashPath` method, what parameters pass to it and an example output. You could provide a simple example showing how to draw a dashed line using `canvas.drawLine()`.

**Comment by dnfield** [comment]
You create your `Path` and wrap it with dashPath.

E.g.

`dashPath(Path()..cubicTo(....)`
